site_name: Administració de Sistemes Operatius
site_description: Materials del mòdul d'Administració de Sistemes Operatius
site_author: María Bañuls

theme:
  name: material
  language: ca

  features:
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Inici: index.md

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - pymdownx.details
  - pymdownx.superfences